# Backend configuration for DEV environment
bucket         = "mychoasss-terraform-state-bucket-chatbot"
key            = "chatbot-service/dev/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "mychoasss-terraform-state-lock"
encrypt        = true

